// create a user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Bintang",
    "email": "bintang@gmail.com",
    "password": "bintang",
    "confirmPassword": "bintang",
    "role": "user"
}

###
// create an admin
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Admin",
    "email": "admin@gmail.com",
    "password": "admin",
    "confirmPassword": "admin",
    "role": "admin"
}

###
// get All Users
GET http://localhost:5000/users

###
// get single user
GET http://localhost:5000/users/ffc1a2b8-7848-4a7e-b742-b69410432f7d

###
PATCH http://localhost:5000/users/ffc1a2b8-7848-4a7e-b742-b69410432f7d
Content-Type: application/json

{
    "name": "Bintang update",
    "email": "bintangupdate@gmail.com",
    "password": "",
    "confirmPassword": "",
    "role": "user"
}

###
DELETE  http://localhost:5000/users/ffc1a2b8-7848-4a7e-b742-b69410432f7d

###
// login admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "admin"
}

###
// login user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "bintang@gmail.com",
    "password": "bintang"
}

###
GET http://localhost:5000/me

###
DELETE http://localhost:5000/logout

###
// get all products
GET http://localhost:5000/products

###
// get single products
GET http://localhost:5000/products/85dcc673-a539-4f9a-811b-65cb9cebacc0

###
// post data product
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "product admin 2",
    "price": 7000
}

###
// update data product
PATCH http://localhost:5000/products/85dcc673-a539-4f9a-811b-65cb9cebacc0
Content-Type: application/json

{
    "name": "product admin updated",
    "price": 7000
}

###
DELETE http://localhost:5000/products/247d2894-3e8d-4d88-b4bb-409639eddd7a

