GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJhaG1hZCIsImVtYWlsIjoiYWhtYWRAZ21haWwuY29tIiwiaWF0IjoxNjk0OTU2MDkxLCJleHAiOjE2OTQ5NTYxMDZ9.6AmNQCnRRJCR-tpdEZkpJ1e0_HEXspj6bE_6div2f80
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "abdul",
    "email": "abdul@gmail.com",
    "password": "123",
    "confPassword": "1234"
}
###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "ahmad@gmail.com",
    "password": "123"
}
###
GET http://localhost:5000/token
###
POST http://localhost:5000/coba
Content-Type: application/json

{
    "email": "ahmad@gmail.com",
    "password": "123h"
}